"""empty message

Revision ID: 9c7655704030
Revises: 
Create Date: 2017-05-04 11:07:27.350503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7655704030'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild', sa.Column('captain', sa.String(length=128), nullable=True))
    op.add_column('guild', sa.Column('officer', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'guild', 'player', ['officer'], ['id'])
    op.create_foreign_key(None, 'guild', 'player', ['captain'], ['id'])
    op.add_column('team', sa.Column('captain', sa.String(length=128), nullable=True))
    op.add_column('team', sa.Column('officer', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'team', 'player', ['officer'], ['id'])
    op.create_foreign_key(None, 'team', 'player', ['captain'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'officer')
    op.drop_column('team', 'captain')
    op.drop_constraint(None, 'guild', type_='foreignkey')
    op.drop_constraint(None, 'guild', type_='foreignkey')
    op.drop_column('guild', 'officer')
    op.drop_column('guild', 'captain')
    # ### end Alembic commands ###
