"""empty message

Revision ID: 9dd963c6b89b
Revises: f08c114e4b20
Create Date: 2017-05-03 19:05:45.538000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dd963c6b89b'
down_revision = 'f08c114e4b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_challenge', sa.Column('mode', sa.String(length=128), nullable=True))
    op.drop_column('guild_challenge', 'category')
    op.add_column('team_challenge', sa.Column('mode', sa.String(length=128), nullable=True))
    op.drop_column('team_challenge', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_challenge', sa.Column('category', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('team_challenge', 'mode')
    op.add_column('guild_challenge', sa.Column('category', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('guild_challenge', 'mode')
    # ### end Alembic commands ###
