"""empty message

Revision ID: b563d08844fb
Revises: c41f62ed89bd
Create Date: 2017-04-27 08:35:02.137000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b563d08844fb'
down_revision = 'c41f62ed89bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roster', sa.Column('team_api', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roster', 'team_api')
    # ### end Alembic commands ###
