"""empty message

Revision ID: bff1937965de
Revises: ec13a7545e13
Create Date: 2017-05-02 18:36:26.467000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff1937965de'
down_revision = 'ec13a7545e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild', sa.Column('captain', sa.String(length=128), nullable=True))
    op.add_column('guild', sa.Column('officer', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'guild', 'player', ['captain'], ['id'])
    op.create_foreign_key(None, 'guild', 'player', ['officer'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guild', type_='foreignkey')
    op.drop_constraint(None, 'guild', type_='foreignkey')
    op.drop_column('guild', 'officer')
    op.drop_column('guild', 'captain')
    # ### end Alembic commands ###
