"""empty message

Revision ID: c41f62ed89bd
Revises: f3db69a63786
Create Date: 2017-04-23 13:14:57.117000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41f62ed89bd'
down_revision = 'f3db69a63786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('createdAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'createdAt')
    # ### end Alembic commands ###
