"""empty message

Revision ID: cbc4d45fccaf
Revises: b563d08844fb
Create Date: 2017-05-01 18:18:26.932000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc4d45fccaf'
down_revision = 'b563d08844fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('team1_id', sa.String(length=128), nullable=True),
    sa.Column('team2_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['team1_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'guild', sa.Column('elo', sa.Integer(), nullable=True))
    op.add_column(u'team', sa.Column('elo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'team', 'elo')
    op.drop_column(u'guild', 'elo')
    op.drop_table('challenge')
    # ### end Alembic commands ###
