"""empty message

Revision ID: e2e7563201a7
Revises: bff1937965de
Create Date: 2017-05-02 19:11:56.112000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2e7563201a7'
down_revision = 'bff1937965de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_challenge',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('guild1_id', sa.String(length=128), nullable=True),
    sa.Column('guild2_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['guild1_id'], ['guild.id'], ),
    sa.ForeignKeyConstraint(['guild2_id'], ['guild.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_challenge',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('team1_id', sa.String(length=128), nullable=True),
    sa.Column('team2_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['team1_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('challenge')
    op.add_column(u'team', sa.Column('captain', sa.String(length=128), nullable=True))
    op.add_column(u'team', sa.Column('officer', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'team', 'player', ['captain'], ['id'])
    op.create_foreign_key(None, 'team', 'player', ['officer'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column(u'team', 'officer')
    op.drop_column(u'team', 'captain')
    op.create_table('challenge',
    sa.Column('id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('team1_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('team2_id', mysql.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['team1_id'], [u'team.id'], name=u'challenge_ibfk_1'),
    sa.ForeignKeyConstraint(['team2_id'], [u'team.id'], name=u'challenge_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('team_challenge')
    op.drop_table('guild_challenge')
    # ### end Alembic commands ###
