"""empty message

Revision ID: ec13a7545e13
Revises: cbc4d45fccaf
Create Date: 2017-05-01 18:24:31.992000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec13a7545e13'
down_revision = 'cbc4d45fccaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elo',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.String(length=128), nullable=True),
    sa.Column('guild_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'guild', 'elo')
    op.drop_column(u'team', 'elo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'team', sa.Column('elo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'guild', sa.Column('elo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('elo')
    # ### end Alembic commands ###
