"""empty message

Revision ID: f08c114e4b20
Revises: ab7ea8b4ea7b
Create Date: 2017-05-03 19:05:15.539000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08c114e4b20'
down_revision = 'ab7ea8b4ea7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_challenge', sa.Column('category', sa.String(length=128), nullable=True))
    op.add_column('guild_challenge', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('guild_challenge', sa.Column('start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_challenge', 'start')
    op.drop_column('guild_challenge', 'end')
    op.drop_column('guild_challenge', 'category')
    # ### end Alembic commands ###
